output: output/report.html
configs:
- config/config.yaml
source: data/example.csv
source_limits:
  start_date: '2018-04-10 00:00:00'
  end_date: '2018-04-13 23:59:59'
reports:
- SummaryReport
- RepliesReport